### ISSUE TITLE
[FEATURE] conditional terraform providers

### ISSUE THREAD

**Issue by geowatson** [mineiros-io/terramate#864] opened 2023-03-13 10:19 UTC
**Is your feature request related to a problem? Please describe.**
Currently, if you want to add a new provider to a certain stack in your project, you need to update global.tm.hcl as follows:
```terraform
generate_hcl "_providers.gen.tf" {
  condition = global.generate_aws_provider || global.generate_mysql_provider

  content {
    terraform {
      required_providers {
        aws = {
          source  = "hashicorp/aws"
          version = "~> 4.14"
        }
        # add new provider mysql
        mysql = {
          source  = "petoju/mysql"
          version = "~> 3.0.29"
        }
      }
    }
  }
...
```
And after this _every_ stack in the project will be updated, which is not what I would like to do at all.

**Describe the solution you'd like**
Something like conditional tm_merge on multiple content blocks with `terraform.required_providers` would really help.
Conditions work in tm_dynamic right now only.
Maybe some sugar like this:
```terraform

  content {
    terraform {
      condition = tm_try(global.generate_aws_provider, true)
      required_providers {
        aws = {
          source  = "hashicorp/aws"
          version = "~> 4.14"
        }
    }

    terraform {
      condition = tm_try(global.generate_mysql_provider, false)
      required_providers {
        mysql = {
          source  = "petoju/mysql"
          version = "~> 3.0.29"
        }
      }
    }
  }
```

**Comment by mariux** [comment] 2023-03-13 12:00
does the following work for you:

```hcl
tm_dynamic "required_providers" {
   attributes = global.required_providers
}
```

you can dynamically build the providers from a map..

```hcl
globals {
  use_providers = [
    "aws",
    "mysql",
  ]
  available_providers = {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 4.14"
    }
    whatever = {
      source  = "hashicorp/whatever"
      version = "~> 42.23"
    }
    mysql = {
      source  = "petoju/mysql"
      version = "~> 3.0.29"
    }
  }
  required_providers = [ for k, v in global.available_providers : k => v if tm_contains(global.use_providers, k) 
}
```

Code is untested and just shows the principle - it might work though..

You basically define a set of available providers as a global config and a global that creates the actual required values from this information with the information what providers to actually use...

the `use_providers` you can set on a per stack base... so the config is global and you switch them on and off...

if you use a map instead, you could actually turn them on and off more additive... e.g.

```
# in parents/root
globals "use_providers" {
   aws = true
}

# in stack
globals "use_providers" {
   # aws = true is inherited from parent
   mysql = true
}
```

you need to change the logic to calculate required to something like:

```
required_providers = [ for k, v in global.available_providers : k => v if tm_try(global.use_providers[k], false) 
```

happy to answer questions or fix issues in the examples.. as said, untested, due to time constraints at the moment ;)

**Comment by geowatson** [comment] 2023-03-13 13:08
@mariux Thanks for the example!

I tried the latter one, which seems more logical, but i keep getting weird reloads each time i use `terramate generate`. It happens that with the example you provided (I used `vault=true` flag) it will be either:
```terraform
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 4.14"
    }
    vault = {
      source  = "hashicorp/vault"
      version = "~> 3.10"
    }
  }
}
```

or:

```terraform
terraform {
  required_providers {
  }
}
```

Is this somehow related to the map structure itself?
```terraform
_available_providers = {
  aws = {
    source  = "hashicorp/aws"
    version = "~> 4.14"
  }
  vault = {
    source  = "hashicorp/vault"
    version = "~> 3.10"
  }
  postgresql = {
    source  = "cyrilgdn/postgresql"
    version = "~> 1.18.0"
  }
  mysql = {
    source  = "petoju/mysql"
    version = "~> 3.0.29"
  }
}
required_providers = {for k, v in global._available_providers : k => v if tm_try(global.use_providers[k], false)}
```

**Comment by sergeyshevch** [comment] 2023-03-13 13:36
I also tested this solution. Looks like bug related to named globals. If I just use 
```
globals {
  use_providers = {
    // ... 
  }
}
``` 

All works fine. But if I add `globals "use_providers"` somewhere it starts to randomly regenerate stacks.

Terramate v0.2.13

**Comment by mariux** [comment] 2023-03-13 13:44
That's an odd behavior that was existing in early version of the labeled globals.. I will try to reproduce this asap... cc @i4ki

**Comment by mariux** [comment] 2023-03-13 14:02
I can confirm the behavior... @i4ki seems there is an evaluation race between constructing the `use_providers` object and using the constructed object in the evaluation of the loop in `required_providers`. 

So randomness is only visible in `required_providers` not in the `use_providers` in this example (which was the bug in early versions of the feature)..

**Comment by mariux** [comment] 2023-03-13 14:19
Once the bug is fixed, does this potentially match as a valid solution for your initial request @geowatson?

**Comment by sergeyshevch** [comment] 2023-03-13 14:28
Yeah, it will totally match our case. Thanks!

**Comment by mariux** [comment] 2023-03-15 18:42
closing.. this should be fixed now with the latest release.. please test and reopen if you feel there is more needed ;)

**Closed by mariux** 2023-03-15 18:42 UTC
Labels: enhancement

**Comment by crileroro** [comment] 2023-12-21 14:34
Hi @soerenmartius @soerenmartius 
Thank you for the example! It is pretty clear how to create dynamically providers. I have a challenge now when it comes to dynamic provider config for some providers, for example Kubernetes. Following the same configuration as in the example and having the following `globals`, I got the error `loading globals: global eval: unknown variable namespace: data`.
```
globals "terraform" "providers" "kubernetes" {
  source  = "hashicorp/kubernetes"
  version = "~> 2.23.0"
  config = {
    host                   = data.aws_eks_cluster.eks.endpoint
    cluster_ca_certificate = base64decode(data.aws_eks_cluster.eks.certificate_authority[0].data)
    token                  = data.aws_eks_cluster_auth.eks.token
  }
}
```

If I add quotes, it generates the config provider ofc but now the Kubernetes provider attributes will be created as strings (`"data.aws_eks_cluster.eks.endpoint"` instead of `data.aws_eks_cluster.eks.endpoint`).
How can I handle this use case with Terramate?
Thanks!

**Comment by aalbright-sovrn** [comment] 2025-02-19 23:39
@crileroro Would you mind sharing your generate_hcl for providers and how you implemented this? I'm running into the same issue.

**Comment by crileroro** [comment] 2025-02-24 08:38
hey @aalbright-sovrn, sure. This is my `generate_hcl` for providers:
```
generate_hcl "_versions.tf" {

  lets {
    required_providers = { for k, v in tm_try(global.terraform.providers, {}) :
      k => {
        source  = v.source
        version = v.version
        } if tm_alltrue([
          tm_try(v.enabled, false),
          tm_length(tm_split(".", k)) == 1,
      ])
    }

    providers = { for k, v in tm_try(global.terraform.providers, {}) :
      k => v.config if tm_alltrue([
        tm_length(tm_split(".", k)) == 1,
        tm_try(v.enabled, false),
        tm_can(v.config)
      ])
    }
  }

  content {
    terraform {
      required_version = tm_try(global.terraform.version, "~>1.7")

      tm_dynamic "required_providers" {
        attributes = let.required_providers
      }

      tm_dynamic "backend" {
        condition = tm_can(global.backend)
        labels    = [global.backend.name]

        attributes = global.backend.config
      }
    }

    tm_dynamic "provider" {
      labels    = ["aws"]
      condition = tm_can(let.providers["aws"])

      content {
        region = let.providers["aws"].region
      }
    }

    tm_dynamic "provider" {
      labels    = ["kubernetes"]
      condition = tm_can(let.providers["kubernetes"])

      content {
        host                   = tm_hcl_expression(let.providers["kubernetes"].host)
        cluster_ca_certificate = tm_hcl_expression(let.providers["kubernetes"].cluster_ca_certificate)
        token                  = tm_hcl_expression(let.providers["kubernetes"].token)
      }
    }
  }
}
```

Then I will just use it with my providers. This is an example of my Kubernetes provider:
```
globals "terraform" "providers" "kubernetes" {
  source  = "hashicorp/kubernetes"
  version = "~> 2.23.0"
  config = {
    host                   = "data.aws_eks_cluster.eks.endpoint"
    cluster_ca_certificate = "base64decode(data.aws_eks_cluster.eks.certificate_authority[0].data)"
    token                  = "data.aws_eks_cluster_auth.eks.token"
  }
}
```

I am passing the Kubernetes provider config attributes as strings that then are going to be injected in a Terramate function `tm_hcl_expression`

**Comment by i4ki** [comment] 2025-02-24 14:18
@aalbright-sovrn @crileroro 

I have this drafted for several months, let me know if it works for your use cases:
https://github.com/terramate-io/terramate-examples/pull/27/files


Using it you can configure providers containing unknowns like below:
```
globals "terraform" "providers" "kubernetes" {
  source  = "hashicorp/kubernetes"
  version = "~> 2.23.0"
  config = {
    # here goes things evaluated at Terramate runtime
  }

  config_partial = {
    # here goes things that evaluates at Terraform time.

    host                   = "data.aws_eks_cluster.eks.endpoint"
    cluster_ca_certificate = "base64decode(data.aws_eks_cluster.eks.certificate_authority[0].data)"
    token                  = "data.aws_eks_cluster_auth.eks.token"
  }
}
```

it merges both `config` and `config_partial` keyvals in the generated `provider` block.
